#!/bin/bash

print_usage () {
    echo -e "Exports the CFG files specified in a CSV file generated by OPL Manager."
	echo -e "This is useful for getting only the CFG files for the games in your list."
    echo -e "Usage:\n"
	echo -e "${0} <CSV game list file> <input CFG folder> <exported CFG folder>\n\n"
}

# Main

if [[ "$#" -ne 3 ]]; then
	print_usage
	exit 0
else
    mkdir -p ${3}

    # Skip the first two lines of the CSV file
    LINES_TO_SKIP=2
    while IFS= read -r line
    do
        if [[ "$LINES_TO_SKIP" -eq 0 ]]; then
            CFG_NAME=$(echo ${line} | cut -d ',' -f2)
            echo "Exporting ${CFG_NAME}.cfg"
            cp ${2}/${CFG_NAME}.cfg ${3}/${CFG_NAME}.cfg
        else
            LINES_TO_SKIP="$((${LINES_TO_SKIP}-1))"
        fi
    done < "${1}"
fi